
services:
  mariadb:
    image: mariadb:10.11.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dsa133WQ
      MYSQL_DATABASE: training
      MYSQL_USER: php 
      MYSQL_PASSWORD: dqLK129d
    ports:
      - "3307:3306"
    volumes:
      - "./data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: php
      PMA_PASSWORD: dqLK129d
    ports:
      - "981:80"
    depends_on:
      - mariadb 
    
volumes:
  data: