controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\AuthController::login

app_register:
    path: /register
    controller: App\Controller\AuthController::register

app_logout:
    path: /logout